Hung added 3 folder CalendarView, TaskListView and TaskView
lonhattan007/uwc-frontend pull request #26
Opened 2023-04-17 04:30 UTC by Hung2002FromDakLak

2023-04-17 12:15 UTC, lonhattan007 requested changes
Tham khảo lại cấu trúc của các page khác trên nhánh `main`

2023-04-17 12:15 UTC, lonhattan007 commented on src/components/App/App.jsx
`App` chỉ là component mẫu, tạo component riêng cho `CalendarView`, tham khảo nhánh `main`

2023-04-17 12:15 UTC, lonhattan007 commented on src/components/TaskView/MapRoute.jpg
Nên đưa vào assets

2023-04-17 12:15 UTC, lonhattan007 commented on src/components/TaskView/maproute.webp
Nên đưa vào assets

2023-04-18 07:29 UTC, Hung2002FromDakLak commented on src/components/App/App.jsx
em vừa chỉnh lại cấu trúc rồi á anh

2023-04-19 08:38 UTC, merged